apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd

spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc

  source:
    repoURL: https://github.com/lobis/argocd-rucio.git
    targetRevision: main
    path: apps

  project: default

  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

